name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        python-version: [ 3.11 ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install package
        run: pip install -e '.[tests]'

      - name: Run Tests
        run: pytest

      - name: Report coverage
        run: "coveralls --service=github"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

